---
# maintain /etc/hosts
# future idea: copy local file

- name: update /etc/hosts
  blockinfile:
      path: /etc/hosts
      block: ""
      marker: "# {mark} ansible managed block written by wick server"
  become: yes
